########################################################################################################################################################
########################################################################################################################################################
#
#   ______         _____  ______  _______              _____  _______  ______ _______ _______      _______  _____  __   _ _______ _____  ______
#  |  ____ |      |     | |_____] |_____| |           |_____] |_____| |_____/ |_____| |  |  |      |       |     | | \  | |______   |   |  ____
#  |_____| |_____ |_____| |_____] |     | |_____      |       |     | |    \_ |     | |  |  |      |_____  |_____| |  \_| |       __|__ |_____|
#
#
########################################################################################################################################################
########################################################################################################################################################

[plotting]
    save = true

    [plotting.fig.training_set]
        save = false

    [plotting.fig.training_set_histogram]
        save = false

    [plotting.fig.bsc_dpl_rangespec]
        save = false

    [plotting.fig.plot_spectra_cwt]
        save = false

    [plotting.generic]
        fig_size = [12, 7]
        range_interval = [0, 12000]
        range_converter = true
        contour = true
        dpi = 200

[tensorflow]

    USE_MODEL = 'conv1d'

    DEVICE = 0

    BATCH_SIZE   = 64   # √
    BATCH_NORM   = true
    EPOCHS       = 25

    #KERNEL_INITIALIZER = 'random_normal'
    #REGULARIZER = 'l1_l2'

    DENSE_LAYERS  = [512, 256, 256]
    DROPOUT      = 0.25

    # binary classifier
    OPTIMIZER   = 'adam'
    ACTIVATIONS  = 'elu'
    ACTIVATIONS_OL  = 'softmax'
    LOSS_FCNS    = 'CategoricalCrossentropy'

    LEARNING_RATE = 1.0e-4
    DECAY_RATE = 1.0e-5
    MOMENTUM = 0.9

    # define paths
    VOODOO_PATH  = '/home/sdig/code/larda3/voodoo/'

    KERNEL_SIZE  = [5, 5, 3, 3]
    STRIDE_SIZE  = [1, 1, 1, 1]
    POOL_SIZE    = [4, 4, 4, 2]
    NFILTERS     = [64, 128, 256, 512]


# define normalization boundaries and conversion for radar (feature) and lidar (label) space
[feature]
    quick_check = false

    [feature.generic]
        scaling = '-'
        use = false

    [feature.VSpec]
        use = true
        var_lims = [1.0e-7, 1.0e2]
        var_converter= 'lin2z'
        scaling = 'normalize'
        despeckle2D = true          # 2D convolution (5x5 window), removes single non-zero values,
        main_peak = true            #
        ghost_echo_1 = true         # reduces the domain (Nyquist velocitdy) by ± 2.5 [m/s], when signal > 0 [dBZ] within 200m above antenna
        ghost_echo_2 = true         #

