########################################################################################################################################################
########################################################################################################################################################
#
#   ______         _____  ______  _______              _____  _______  ______ _______ _______      _______  _____  __   _ _______ _____  ______
#  |  ____ |      |     | |_____] |_____| |           |_____] |_____| |_____/ |_____| |  |  |      |       |     | | \  | |______   |   |  ____
#  |_____| |_____ |_____| |_____] |     | |_____      |       |     | |    \_ |     | |  |  |      |_____  |_____| |  \_| |       __|__ |_____|
#
#
########################################################################################################################################################
########################################################################################################################################################

[plotting]
    save = true

    [plotting.fig.training_set]
        save = false

    [plotting.fig.training_set_histogram]
        save = false

    [plotting.fig.bsc_dpl_rangespec]
        save = false

    [plotting.fig.plot_spectra_cwt]
        save = false

    [plotting.generic]
        fig_size = [12, 7]
        range_interval = [0, 12000]
        range_converter = true
        contour = true
        dpi = 200

[tensorflow]

    USE_MODEL = 'conv1d'

    BATCH_SIZE   = 32   # √
    BATCH_NORM   = true
    EPOCHS       = 25

    DENSE_LAYERS = [3]
    DENSE_NODES  = [32, 32, 32]
    DROPOUT      = 0.70

    # binary classifier
    OPTIMIZERS   = ['adam']
    ACTIVATIONS  = ['relu']
    ACTIVATIONS_OL  = 'softmax'
    LOSS_FCNS    = ['CategoricalCrossentropy']

    LEARNING_RATE = [1.0e-4]
    DECAY_RATE = 1.0e-5
    MOMENTUM = 0.99

    # define paths
    VOODOO_PATH  = '/home/sdig/code/larda3/voodoo/'

    [tensorflow.conv2d]
        CONV_LAYERS  = [3]
        KERNEL_SIZE  = [3, 3]
        STRIDE_SIZE  = [2, 1]
        POOL_SIZE    = [2, 2]
        NFILTERS     = [128, 256, 512]

    [tensorflow.conv1d]
        CONV_LAYERS  = [2]
        KERNEL_SIZE  = [5]
        STRIDE_SIZE  = [1]
        POOL_SIZE    = [2]
        NFILTERS     = [32, 64, 128]


# define normalization boundaries and conversion for radar (feature) and lidar (label) space
[feature.info]
    quick_check = false

    [feature.info.generic]
        scaling = '-'
        use = false

    [feature.info.VSpec]
        use = true
        var_lims = [1.0e-7, 1.0e2]
        var_converter= 'lin2z'
        scaling = 'normalize'
        despeckle2D = true          # 2D convolution (5x5 window), removes single non-zero values,
        main_peak = true            #
        ghost_echo_1 = true         # reduces the domain (Nyquist velocitdy) by ± 2.5 [m/s], when signal > 0 [dBZ] within 200m above antenna
        ghost_echo_2 = true         #

    [feature.info.Ze]
        var_lims = [1.0e-6, 1.0e2]
        var_converter= '-'

    [feature.info.VEL]
        var_lims = [-6.0, 4.0]
        var_converter= '-'

    [feature.info.sw]
        var_lims = [0.0, 3.0]
        var_converter= '-'

    [feature.info.skew]
        var_lims = [-3.0, 3.0]
        var_converter= '-'

    [feature.info.kurt]
        var_lims = [0.0, 3.0]
        var_converter= '-'

    [feature.info.cwt]
        use = true
        var_lims = [0.0, 1.0]
        var_converter = []
        scales = [1.25, 10.0, 32.0]
        scaling = 'normalize'
        plot = false

    [feature.info.fft]
        use = true
        var_lims = [0.0, 10.0]
        var_converter = []
        scaling = 'normalize'
        plot = false


# define normalization boundaries and conversion for radar (feature) and lidar (label) space
[target.info]
    [target.info.generic]
        scaling = 'normalize'

    [target.info.attbsc1064]
        var_lims = [1.0e-7, 1.0e-3]
        var_converter= 'log'
        scaling = ''
        use = false

    [target.info.depol]
        var_lims = [1.0e-7, 0.3]
        var_converter= 'ldr2cdr'
        scaling = ''
        use = false

