########################################################################################################################################################
########################################################################################################################################################
#
#   ______         _____  ______  _______              _____  _______  ______ _______ _______      _______  _____  __   _ _______ _____  ______
#  |  ____ |      |     | |_____] |_____| |           |_____] |_____| |_____/ |_____| |  |  |      |       |     | | \  | |______   |   |  ____
#  |_____| |_____ |_____| |_____] |     | |_____      |       |     | |    \_ |     | |  |  |      |_____  |_____| |  \_| |       __|__ |_____|
#
#
########################################################################################################################################################
########################################################################################################################################################

[statistics]
    exclude_drizzle = 'rg0drizzle'  #   ['disdro', 'anydrizzle', 'rg0drizzle']
    exclude_wet_radome_mwr = 6  #   numer ob time steps after precipitation (1 = 30sec)

[plotting]
    save = true

    [plotting.generic]
        fig_size = [12, 7]
        range_interval = [0, 12000]
        range_converter = true
        contour = true
        dpi = 200

[pytorch]

    BATCH_SIZE   = 128 # √
    batch_norm   = true
    EPOCHS       = 1

    #kernel_init = 'random_uniform'
    #regularizer = 'l1_l2'

    dense_layers  = [256, 256, 256, 256, 128]
    #dense_layers  = [512, 512, 256, 128]
    dropout      = 0.25

    OPTIMIZER   = 'adam'

    # why elu? --> https://arxiv.org/pdf/1511.07289.pdf
    hidden_activations  = 'elu'    # 'relu

    # image classification
    output_activation  = 'softmax'
    LOSS_FCNS    = 'SparseCategoricalCrossentropy'
    metrics = ['sparse_categorical_accuracy']

    LEARNING_RATE = 1.0e-4
    DECAY_RATE = 1.0e-5
    MOMENTUM = 0.9

    # define paths
    VOODOO_PATH  = '/home/sdig/code/larda3/voodoo/'


    kernel_sizes  = [[1, 3], [1, 1], [1, 3], [1, 1], [1, 3], [1, 1]]
    pad_sizes     = [[1, 3], [1, 1], [1, 3], [1, 1], [1, 3], [1, 1]]
    stride_sizes  = [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]
    pool_sizes    = [[1, 2], [1, 1], [1, 2], [1, 1], [2, 4], [1, 4]]
    num_filters   = [512, 256, 1024, 512, 1024, 512]


# define normalization boundaries and conversion for radar (feature) and lidar (label) space
[feature]
    quick_check = true
    remove_ice = 0.0       # remove percentage of samples
    remove_drizzle = 0.0   # remove percentage of samples
    n_validation = 5        # use 1 out of n_validation samples for validation

    [feature.generic]
        scaling = '-'
        use = false

    [feature.VSpec]
        use = true
        add_flipped = false
        var_lims = [1.0e-7, 1.0e2]
        var_converter= 'lin2z'
        scaling = 'normalize'
        despeckle2D = true          # 2D convolution (5x5 window), removes single non-zero values,
        main_peak = true            #
        ghost_echo_1 = false         # reduces the domain (Nyquist velocitdy) by ± 2.5 [m/s], when signal > 0 [dBZ] within 200m above antenna
        ghost_echo_2 = true         #
        dealiasing = false         #
        add_horizontal_channel = true


# define normalization boundaries and conversion for radar (feature) and lidar (label) space
[target.info]
    [target.info.generic]
        scaling = 'normalize'

    [target.info.attbsc1064]
        var_lims = [1.0e-7, 1.0e-3]
        var_converter= 'log'
        scaling = ''
        use = false

    [target.info.depol]
        var_lims = [1.0e-7, 0.3]
        var_converter= 'ldr2cdr'
        scaling = ''
        use = false

