########################################################################################################################################################
########################################################################################################################################################
#
#   ______         _____  ______  _______              _____  _______  ______ _______ _______      _______  _____  __   _ _______ _____  ______
#  |  ____ |      |     | |_____] |_____| |           |_____] |_____| |_____/ |_____| |  |  |      |       |     | | \  | |______   |   |  ____
#  |_____| |_____ |_____| |_____] |     | |_____      |       |     | |    \_ |     | |  |  |      |_____  |_____| |  \_| |       __|__ |_____|
#
#
########################################################################################################################################################
########################################################################################################################################################

[instruments]
    cloudnet = ['CLASS', 'detection_status', 'Z', 'VEL', 'VEL_sigma', 'width', 'Tw', 'insect_prob', 'beta', 'category_bits', 'quality_bits']
    cloudnet_ts = ['LWP']
    model = ['T', 'P', 'q', 'UWIND', 'VWIND']
    lidar = ['attbsc1064', 'attbsc532', 'depol']

[larda]
    path = '/home/sdig/code/larda3/larda/'
    params = ['filename', 'system', 'colormap', 'rg_unit', 'var_unit']
