[pytorch]
    fn = 'dbg'
    p = 0.375
    resnet = 'VN'

    dense_layers = [128]
    dropout = 0.0
    batch_size = 512
    epochs = 2
    balance = -1
    remove_classes = []
    garbage_classes = []

    optimizer  = 'adam'

    # why elu? --> https://arxiv.org/pdf/1511.07289.pdf
    hidden_activations = 'elu'    # 'relu
    output_activation = 'softmax'
    loss = 'crossentropy'
    metrics = ['sparse_categorical_accuracy']

    learning_rate = 1.0e-4

    kernel_sizes  = [[3, 3], [3, 3], [1, 3], [1, 3], [1, 3]]
    pad_sizes     = [[1, 1], [1, 1], [0, 1], [0, 1], [0, 1]]
    stride_sizes  = [[1, 2], [1, 2], [1, 2], [2, 2], [1, 2]]
    num_filters   = [16, 32, 64, 128, 256]



