
[pytorch]
    iGPU = 0
    fn = 'dbg'
    p = 0.25

    resnet = 'VN'

    #kernel_init = 'random_uniform'
    #regularizer = 'l1_l2'
    dense_layers = [128]
    dropout = 0.0
    batch_size = 512
    epochs = 2
    balance = -1
    remove_classes = []
    garbage_classes = []

    learning_rate = 1.0e-4
    #momentum = 0.999
    #optimizer  = 'sgd'
    optimizer  = 'adam'
    # why elu? --> https://arxiv.org/pdf/1511.07289.pdf
    hidden_activations  = 'elu'    # 'relu

    # image classification
    output_activation  = 'softmax'
    loss    = 'crossentropy'
    metrics = ['sparse_categorical_accuracy']

    kernel_sizes  = [[1, 3], [1, 3], [1, 3], [1, 3], [1, 3]]
    pad_sizes     = [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]
    stride_sizes  = [[1, 2], [1, 2], [1, 2], [2, 2], [1, 2]]
    #pool_sizes    = [[1, 2], [1, 2], [1, 2], [2, 2], [1, 2]]
    num_filters   = [16, 32, 64, 128, 256]



